version: "3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}"
    container_name: "elasticsearch"
    restart: "always"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      net:
        ipv4_address: "10.10.10.1"
    deploy:
      resources:
        limits:
          memory: "1024M"
        reservations:
          memory: "512M"

  kibana:
    image: "docker.elastic.co/kibana/kibana:${KIBANA_VERSION}"
    container_name: "kibana"
    restart: "always"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=false"
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      net:
        ipv4_address: "10.10.10.2"
    deploy:
      resources:
        limits:
          memory: "1024M"
        reservations:
          memory: "512M"

  fluentd:
    build: "./dockerfiles/fluentd"
    container_name: "fluentd"
    restart: "always"
    volumes:
      - "./volume/fluentd/conf:/fluentd/etc"
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      net:
        ipv4_address: "10.10.10.3"
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  semantic:
    image: "openjdk"
    container_name: "ufcity-semantic"
    restart: "always"
    volumes:
      - "./volume/ufcity-semantic:/usr/src/ufcity-semantic"
    working_dir: "/usr/src/ufcity-semantic"
    command: "java -jar ufcity-fog-semantic-${UFCITY_SEMANTIC_VERSION}.jar"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "ufcity-semantic"
    networks:
      net:
        ipv4_address: "10.10.10.4"
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  handler:
    image: "openjdk"
    container_name: "ufcity-handler"
    restart: "always"
    volumes:
      - "./volume/ufcity-handler:/usr/src/ufcity-handler"
    working_dir: "/usr/src/ufcity-handler"
    command: "java -jar ufcity-fog-handler-${UFCITY_HANDLER_VERSION}.jar"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "ufcity-handler"
    networks:
      net:
        ipv4_address: "10.10.10.5"
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  cep:
    image: "openjdk"
    container_name: "ufcity-cep"
    restart: "always"
    volumes:
      - "./volume/ufcity-cep:/usr/src/ufcity-cep"
    working_dir: "/usr/src/ufcity-cep"
    command: "java -jar ufcity-fog-cep-${UFCITY_CEP_VERSION}.jar"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "ufcity-cep"
    networks:
      net:
        ipv4_address: "10.10.10.6"
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  mqtt:
    image: "eclipse-mosquitto:${MOSQUITTO_VERSION}"
    container_name: "mqtt"
    restart: "always"
    volumes:
      - "./volume/mqtt/mosquitto:/mosquitto"
      - "./volume/mqtt/mosquitto/config:/mosquitto/config"
      - "./volume/mqtt/mosquitto/data:/mosquitto/data"
      - "./volume/mqtt/mosquitto/log:/mosquitto/log"
    ports:
      - "1883:1883"
      - "9001:9001"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "mqtt"
    networks:
      net:
        ipv4_address: "10.10.10.7"
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  fuseki:
    image: "stain/jena-fuseki"
    container_name: "fuseki"
    restart: "always"
    ports:
      - "3030:3030"
    environment:
      - "ADMIN_PASSWORD=${FUSEKI_ADMIN_PASSWORD}"
      - "TDB=2"
      - "FUSEKI_DATASET_1=ufcity-ont"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "fuseki"
    networks:
      net:
        ipv4_address: "10.10.10.8"
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  mongo:
    image: "mongo:${MONGO_VERSION}"
    container_name: "mongo"
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "mongo"
    networks:
      net:
        ipv4_address: "10.10.10.9"
    deploy:
      resources:
        limits:
          memory: "512M"
        reservations:
          memory: "256M"

  mongo-express:
    image: "mongo-express:${MONGO_EXPRESS_VERSION}"
    container_name: "mongo-express"
    restart: "always"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "mongo-express"
    networks:
      net:
        ipv4_address: "10.10.10.10"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  fog-webpage:
    image: "httpd"
    container_name: "fog-webpage"
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - "./volume/fog-webpage:/usr/local/apache2/htdocs/"
    links:
      - "fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "fog-webpage"
    networks:
      net:
        ipv4_address: "10.10.10.11"
    deploy:
      resources:
        limits:
          memory: "256M"
        reservations:
          memory: "128M"

networks:
  net:
    driver: "bridge"
    ipam:
      config:
        - subnet: "10.10.10.0/8"