version: "3"
services:
  edge-com:
    image: eclipse-mosquitto
    container_name: edge-com
    hostname: edge-com
    restart: always
    volumes:
      - ./volume/edge-com/mosquitto:/mosquitto
      - ./volume/edge-com/mosquitto/config:/mosquitto/config
      - ./volume/edge-com/mosquitto/data:/mosquitto/data
      - ./volume/edge-com/mosquitto/log:/mosquitto/log
    ports:
      - "1884:1883"
      - "9004:9001"    
    networks:
      - edge-net

  inner-com:
    image: eclipse-mosquitto
    container_name: inner-com
    hostname: inner-com
    restart: always
    volumes:
      - ./volume/inner-com/mosquitto:/mosquitto
      - ./volume/inner-com/mosquitto/config:/mosquitto/config
      - ./volume/inner-com/mosquitto/data:/mosquitto/data
      - ./volume/inner-com/mosquitto/log:/mosquitto/log
    ports:
      - "1885:1883"
      - "9005:9001"    
    networks:
      - inner-net

  cloud:
    image: eclipse-mosquitto
    container_name: cloud
    hostname: cloud
    restart: always
    volumes:
      - ./volume/cloud/mosquitto:/mosquitto
      - ./volume/cloud/mosquitto/config:/mosquitto/config
      - ./volume/cloud/mosquitto/data:/mosquitto/data
      - ./volume/cloud/mosquitto/log:/mosquitto/log
    ports:
      - "1886:1883"
      - "9006:9001"    
    networks:
      - inner-net

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - inner-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - inner-net

  fuseki:
    image: zacanbot/fuseki
    container_name: fuseki
    hostname: fuseki
    environment:
        JVM_ARGS: -Xmx4g
    volumes:
      - ./volume/fuseki-server/data:/data/fuseki
    ports:
      - "4040:3030"
    networks:
      - inner-net

  handler:
    image: openjdk
    container_name: ufcity-handler
    hostname: ufcity-handler
    restart: always
    volumes:
      - ./volume/ufcity-handler:/usr/src/ufcity-handler
    working_dir: /usr/src/ufcity-handler
    command: java -jar ufcity-fog-handler-1.0-SNAPSHOT.jar
    networks:
      - edge-net
      - inner-net
      
networks:
  inner-net:
    driver: "bridge"
  edge-net:
    driver: "bridge"


  # traking:
  #   image: openjdk
  #   container_name: ufcity-traking
  #   # restart: always
  #   volumes:
  #     - ./volume/ufcity-traking:/usr/src/ufcity-traking
  #   working_dir: /usr/src/ufcity-traking
  #   command: java -jar ufcity-fog-traking.jar
  #   networks:
  #     - inner-net
  #     - north-net

# ubuntu:
#   image: ubuntu:jammy
#   container_name: ubuntu
#   networks:
#     - inner-net
